import Head from "next/head"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="p-12 w-full h-screen flex items-center justify-center">
				<h1 className="text-6xl font-bold">Choose User</h1>
			</main>
		</>
	)
}
