import Head from "next/head"
import { LoginForm } from "@/components/pages/login"

export default function Home() {
	return (
		<>
			<Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="p-12 w-full h-screen flex items-center justify-center">
				<div className="flex flex-col gap-8 items-center w-full">
					<h1 className="text-6xl font-bold">Login</h1>
					<LoginForm />
				</div>
			</main>
		</>
	)
}
